apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: infra-base-template
  title: Template base de infraestrutura
  description: Criar infraestrutura base
  tags:
    - recommended
    - terraform
spec:
  owner: web@example.com
  type: infra

  parameters:
    - title: Parametros gerais da infraestrutura
      required:
        - project_name
        - region
        - owner
      properties:
        project_name:
          title: Nome do projeto
          type: string
          description: Nome do projeto
        region:
          title: Regiao
          type: string
          default: "us-east-1"
          description: Regiao da AWS que serao criados os recursos de infra. Ex (us-east-1)
        owner:
          title: Dono
          type: string
          description: Dono do componente
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

    # - title: Parametros da infraestrutura de producao
    #   required:
    #     - bucket_name_prod
    #     - key_path_prod
    #     - cidr_prod
    #     - private_subnets_prod
    #     - public_subnets_prod
    #   properties:
    #     bucket_name_prod:
    #       title: Nome do bucket
    #       type: string
    #       description: Nome do bucket que contem a chave de acesso
    #     key_path_prod:
    #       title: Caminho da chave
    #       type: string
    #       description: Caminho da chave de acesso dentro do bucket
    #     cidr_prodcidr_prod:
    #       title: CIDR
    #       type: string
    #       description: CIDR da VPC. Ex (10.133.0.0/16)
    #     private_subnets_prod:
    #       title: Lista das subnets privadas
    #       type: array
    #       description: Lista das subnets privadas, cada item corresponde a uma subnet. Ex (1° item - "10.133.0.0/20", 2°item - "10.133.16.0/20", 3°item - "10.133.32.0/20"])
    #       items:
    #         type: string
    #     public_subnets_prod:
    #       title: Lista das subnets publicas
    #       type: array
    #       description: Lista das subnets publicas, cada item corresponde a uma subnet. Ex (1° item - "10.133.0.0/20", 2°item - "10.133.16.0/20", 3°item - "10.133.32.0/20"])
    #       items:
    #         type: string
    #     enable_nat_gateway_prod:
    #       title: Habilitar NAT Gateway
    #       type: boolean
    #       default: true
    #       description: Habilitar NAT Gateway na VCP, caso não seja indicado o padrão sera definido como true
    #     single_nat_gateway_prod:
    #       title: NAT Gateway unico
    #       type: boolean
    #       default: true
    #       description: Habilitar NAT Gateway unico na VPC, caso não seja indicado o padrão sera definido como true
    #     enable_dns_hostnames_prod:
    #       title: Habilitar DNS
    #       type: boolean
    #       default: true
    #       description: Habilitar DNS hostnames na VPC, caso não seja indicado o padrão sera definido como true
      # dependencies:
      #   enable_nat_gateway_prod:
      #     oneOf:
      #       - properties:
      #         enable_nat_gateway_prod:
      #           enum:
      #             - true
      #         single_nat_gateway_prod:
      #           type: boolean
      #           title: NAT Gateway unico
      #       - properties:
      #         enable_nat_gateway_prod:
      #           enum:
      #             - false

    - title: Parametros da infraestrutura de qualidade
      required:
        - bucket_name_qa
        - key_path_qa
        - cidr_qa
        - private_subnets_qa
        - public_subnets_qa
      properties:
        bucket_name_qa:
          title: Nome do bucket
          type: string
          description: Nome do bucket que contem a chave de acesso
        key_path_qa:
          title: Caminho da chave
          type: string
          description: Caminho da chave de acesso dentro do bucket
        cidr_qa:
          title: CIDR
          type: string
          description: CIDR da VPC. Ex (10.133.0.0/16)
        private_subnets_prod:
          title: Lista das subnets privadas
          type: array
          description: Lista das subnets privadas, cada item corresponde a uma subnet. Ex (1° item - "10.133.0.0/20", 2°item - "10.133.16.0/20", 3°item - "10.133.32.0/20"])
          items:
            type: string
        public_subnets_prod:
          title: Lista das subnets publicas
          type: array
          description: Lista das subnets publicas, cada item corresponde a uma subnet. Ex (1° item - "10.133.0.0/20", 2°item - "10.133.16.0/20", 3°item - "10.133.32.0/20"])
          items:
            type: string
        enable_nat_gateway_prod:
          title: Habilitar NAT Gateway
          type: boolean
          default: true
          description: Habilitar NAT Gateway na VCP, caso não seja indicado o padrão sera definido como true
        single_nat_gateway_prod:
          title: NAT Gateway unico
          type: boolean
          default: true
          description: Habilitar NAT Gateway unico na VPC, caso não seja indicado o padrão sera definido como true
        enable_dns_hostnames_prod:
          title: Habilitar DNS
          type: boolean
          default: true
          description: Habilitar DNS hostnames na VPC, caso não seja indicado o padrão sera definido como true
          
    - title: Escolher repositorio
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repositorio
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - gitlab.inlabs.app

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .gitlab/workflows/*
        values:
          component_id: '{{ parameters.component_id }}'
          project_name: '{{ parameters.project_name }}'
          bucket_name_prod: '{{ parameters.bucket_name_prod }}'
          key_path_prod: '{{ parameters.key_path_prod }}'
          cidr_prod: '{{ parameters.cidr_prod }}'
          private_subnets_prod: '{{ parameters.private_subnets_prod }}'
          public_subnets_prod: '{{ parameters.public_subnets_prod }}'
          enable_nat_gateway_prod: '{{ parameters.enable_nat_gateway_prod }}'
          single_nat_gateway_prod: '{{ parameters.single_nat_gateway_prod }}'
          enable_dns_hostnames_prod: '{{ parameters.enable_dns_hostnames_prod }}'
          bucket_name_qa: '{{ parameters.bucket_name_qa }}'
          key_path_qa: '{{ parameters.key_path_qa }}'
          cidr_qa: '{{ parameters.cidr_qa }}'
          private_subnets_qa: '{{ parameters.private_subnets_qa }}'
          public_subnets_qa: '{{ parameters.public_subnets_qa }}'
          enable_nat_gateway_qa: '{{ parameters.enable_nat_gateway_qa }}'
          single_nat_gateway_qa: '{{ parameters.single_nat_gateway_qa }}'
          enable_dns_hostnames_qa: '{{ parameters.enable_dns_hostnames_qa }}'

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.inlabs.app']
        description: 'This is {{ parameters.project_name }}'
        repoUrl: '{{ parameters.repoUrl }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
    entityRef: '{{ steps.register.output.entityRef }}'
