apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: infra-base-template
  title: Template base de infraestrutura
  description: Criar infraestrutura base
  tags:
    - recommended
    - terraform
spec:
  owner: web@example.com
  type: infra

  parameters:
    - title: Preencha o nome da entidade
      type: object
      required:
        - entity_name
      properties:
        entity_name:
          title: Entity Name
          type: string
          description: Unique name of the entity
        entity:
          title: Campo
          type: array
          items:
            type: object
            required:
              - prop_name
            properties:
              prop_name:
                type: string
                title: Campo
                description: Nome do campo da entidade
              prop_type:
                type: string
                title: Tipo
                description: Selecione um tipo para o campo
                enum:
                  - String
                  - Integer
                  - Float
                  - Boolean
            dependencies:
              prop_type:
                oneOf:
                  - properties:
                      prop_type:
                        enum:
                          - Integer
                          - Boolean
                  - properties:
                      prop_type:
                        enum:
                          - String
                          - Float
                      prop_size:
                        type: string
                        title: Tamanho
                        description: Tamanho do campo da entidade
                    required:
                      - prop_size
          
    - title: Escolher repositorio
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repositorio
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.inlabs.app

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .gitlab/workflows/*
        values:

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.inlabs.app']
        description: 'This is {{ parameters.project_name }}'
        repoUrl: '{{ parameters.repoUrl }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
    entityRef: '{{ steps.register.output.entityRef }}'
apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: infra-base-template
  title: Template base de infraestrutura
  description: Criar infraestrutura base
  tags:
    - recommended
    - terraform
spec:
  owner: web@example.com
  type: infra

  parameters:
    - title: Preencha o nome da entidade
      type: object
      required:
        - entity_name
      properties:
        entity_name:
          title: Entity Name
          type: string
          description: Unique name of the entity
        entity:
          title: Campo
          type: array
          items:
            type: object
            required:
              - prop_name
            properties:
              prop_name:
                type: string
                title: Campo
                description: Nome do campo da entidade
              prop_type:
                type: string
                title: Tipo
                description: Selecione um tipo para o campo
                enum:
                  - String
                  - Integer
                  - Float
                  - Boolean
            dependencies:
              prop_type:
                oneOf:
                  - properties:
                      prop_type:
                        enum:
                          - Integer
                          - Boolean
                  - properties:
                      prop_type:
                        enum:
                          - String
                          - Float
                      prop_size:
                        type: string
                        title: Tamanho
                        description: Tamanho do campo da entidade
                    required:
                      - prop_size
          
    - title: Escolher repositorio
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repositorio
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.inlabs.app

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .gitlab/workflows/*
        values:

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.inlabs.app']
        description: 'This is {{ parameters.project_name }}'
        repoUrl: '{{ parameters.repoUrl }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
    entityRef: '{{ steps.register.output.entityRef }}'
