apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: infra-eks-template
  title: Template de Infraestrutura Eks
  description: Criar infraestrutura Eks
  tags:
    - recommended
    - terraform
spec:
  owner: web@example.com
  type: infra

  parameters:
    - title: Parametros gerais da infraestrutura
      required:
        - project_name
      properties:
        project_name:
          title: Nome do projeto
          type: string
          description: Nome do projeto
          ui:field: AWSAccountsExtension

    - title: Escolher repositorio
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repositorio
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.inlabs.app
        branch:
          title: Branch
          type: string
          enum: ['master', 'development']
          default: 'master'
          description: 'Branch onde o projeto será comitado'

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .gitlab/workflows/*
        values:
          project_name: '${{ parameters.project_name }}'


    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        defaultBranch: '${{ parameters.branch }}'
        allowedHosts: ['gitlab.inlabs.app']
        description: 'This is ${{ parameters.project_name }}'
        repoUrl: '${{ parameters.repoUrl }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '${{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

  links:
    - title: Repository
      url: ${{ steps.publish.output.remoteUrl }}
    - title: Open in catalog
      icon: catalog
      entityRef: ${{ steps.register.output.entityRef }}
